/** @type {import("tailwindcss").Config} */
export default {
  content: ["./src/**/*!(*.stories|*.spec).{ts,tsx,html}"],
  theme: {
    extend: {
      fontFamily: {
        inter: ["Inter", "sans-serif"],
      },
      colors: {
        primary: "#3E63DD",
        "primary-hover": "#2C48C9",
        "primary-disabled": "#9BBEF5",
        "primary-light": "#F0F5FE",
        "primary-dark": "#273781",
        "static-white": "#FFFFFF",
        "static-black": "#0E121B",
        "background-subtle": "#FFFFFF",
        "background-default": "#F7F8FA",
        "background-surface": "#E6E9F0",
        "background-emphasis": "#DBDDE0",
        "background-overlay": "#0E121B66",
        "foreground-primary": "#1C244F",
        "foreground-secondary": "#717784",
        "foreground-disabled": "#A7A9B8",
        "foreground-inverse": "#FFFFFF",
        "stroke-default": "#DBDDE0",
        "stroke-divider": "#CACFD8",
        "stroke-focus": "#3E63DD",
        "stroke-medium": "#CACFD8",
        "icon-primary": "#3E63DD",
        "icon-default": "#8B919E",
        "icon-disabled": "#C4D8F9",
        "icon-high-contrast": "#FFFFFF",
        "error-dark": "#8B1822",
        "error-primary": "#E93544",
        "error-hover": "#D02533",
        "error-disabled": "#FF97A0",
        "error-background": "#FFEBEC",
        "error-chart": "#FF6875",
        "success-primary": "#1DAF61",
        "success-background": "#E0FAEC",
        "success-disabled": "#C2F5DA",
        "success-chart": "#3EE089",
        "warning-primary": "#E6A819",
        "warning-background": "#FFFAEB",
        "warning-disabled": "#FFECC0",
        "warning-chart": "#FFD268",
        "info-primary": "#3E63DD",
        "info-background": "#F0F5FE",
        "info-disabled": "#C4D8F9",
        "info-chart": "#6C9CEE",
        "stable-primary": "#693EE0",
        "stable-background": "#EFEBFF",
        "stable-disabled": "#CAC0FF",
        "stable-chart": "#8C71F6",
        "pending-primary": "#E16614",
        "pending-background": "#FFF3EB",
        "pending-disabled": "#FFD9C0",
        "pending-chart": "#FFA468",
        ring: "#3E63DD",

        background: "#E7E6F7",
        "background-alt": "#FFFFFF",
        "background-muted": "#E4E8ED",
        "background-muted-more": "#F2F6FB",
        "background-toggle-on": "#3CC274",
        "background-toggle-off": "#E4E8ED",
        foreground: "var(--foreground)",
        "foreground-link": "#AA55EA",
        "foreground-muted": "#6C7585",
        "foreground-muted-more": "#9FA7B2",
        "foreground-accent": "#4E5560",
        "segment-foreground-selected": "#6C309A",
        border: "var(--border)",
        "button-primary-background": "#6C309A",
        "button-primary-foreground": "#FFFFFF",
        "button-tertiary-foreground": "#0E1119",
        "button-tertiary-border": "#D1D6DE",
        "button-ghost-background": "#EDECF9",
        "button-ghost-foreground": "#0E1119",
        "button-ghost-border": "#DACFF5",
        "button-success-background": "#30A059",
        "button-success-foreground": "#FFFFFF",
        "button-destructive-background": "#DC2626",
        "button-destructive-foreground": "#FFFFFF",
        "button-segment-background": "#FFF",
        "button-segment-background-selected": "#EDF2F9",
        "button-segment-foreground": "#4E5560",
        "button-segment-foreground-selected": "#6C309A",
        "button-segment-border": "#E4E8ED",
        "popover-foreground-muted": "#9FA7B2",
        "state-info-background": "#E4E8ED",
        "state-info-foreground": "#141921",
        "state-info-border": "#D1D6DE",
        "state-progress-background": "#EDE8FF",
        "state-progress-foreground": "#6838E0",
        "state-progress-border": "#C5B2FF",
        "state-warning-background": "#FEF3C7",
        "state-warning-foreground": "#CA8A04",
        "state-warning-border": "#F8D34C",
        "state-success-background": "#DDF8E6",
        "state-success-foreground": "#30A059",
        "state-success-border": "#95E5B0",
        "state-destructive-background": "#FEF2F2",
        "state-destructive-foreground": "#B91C1C",
        "state-destructive-foreground-muted": "#DC2626",
        "state-destructive-border": "#FECACA",
        success: "#58bd7d",
        warning: "#ffd300",
        error: "#e42222",
      },
      boxShadow: {
        "black-16": "0px 0px 6px 0px #0E121B29",
      },
      keyframes: {
        "progress-circular-rotate": {
          "100%": {
            transform: "rotate(360deg)",
          },
        },
        "progress-circular-dash": {
          "0%": {
            strokeDasharray: "1, 200",
            strokeDashoffset: 0,
          },
          "50%": {
            strokeDasharray: "100, 200",
            strokeDashoffset: "-15px",
          },
          "100%": {
            strokeDasharray: "100, 200",
            strokeDashoffset: "-124px",
          },
        },
        "drawer-from-left": {
          "0%": {
            transform: "translateX(-400px)",
          },
          "100%": {
            transform: "translateX(0)",
          },
        },
        "drawer-from-right": {
          "0%": {
            right: 0,
            transform: "translateX(400px)",
          },
          "100%": {
            transform: "translateX(0)",
          },
        },
      },
      animation: {
        "progress-circular-rotate": "progress-circular-rotate 1.4s linear infinite",
        "progress-circular-dash": "progress-circular-dash 1.4s ease-in-out infinite",
        "drawer-from-left": "drawer-from-left .2s linear both",
        "drawer-from-right": "drawer-from-right .2s linear both",
      },
    },
  },
  plugins: [],
};
