/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as AccountDetailsAccountDetailsConstsImport } from "./routes/account-details/account-details.consts";
import { Route as AccountDetailsIndexImport } from "./routes/account-details/index";
import { Route as AccountsIndexImport } from "./routes/accounts/index";
import { Route as AdminUserIndexImport } from "./routes/admin-user/index";
import { Route as AdminUsersIndexImport } from "./routes/admin-users/index";
import { Route as ApiKeyDetailsApiKeyDetailsConstsImport } from "./routes/api-key-details/api-key-details.consts";
import { Route as ApiKeyDetailsIndexImport } from "./routes/api-key-details/index";
import { Route as ApiKeysIndexImport } from "./routes/api-keys/index";
import { Route as AssetsIndexImport } from "./routes/assets/index";
import { Route as AuthIndexImport } from "./routes/auth/index";
import { Route as BrandsIndexImport } from "./routes/brands/index";
import { Route as CheckEmailIndexImport } from "./routes/check-email/index";
import { Route as CoinsIndexImport } from "./routes/coins/index";
import { Route as CustomerDepositWithdrawalDetailsIndexImport } from "./routes/customer-deposit-withdrawal-details/index";
import { Route as CustomerProfileCustomerProfileRouteConstsImport } from "./routes/customer-profile/customer-profile.consts";
import { Route as CustomerProfileIndexImport } from "./routes/customer-profile/index";
import { Route as CustomersIndexImport } from "./routes/customers/index";
import { Route as DepositWithdrawalDetailsIndexImport } from "./routes/deposit-withdrawal-details/index";
import { Route as DepositsWithdrawalsDepositWithdrawalsConstsImport } from "./routes/deposits-withdrawals/deposit-withdrawals.consts";
import { Route as DepositsWithdrawalsIndexImport } from "./routes/deposits-withdrawals/index";
import { Route as FeeSettingsFeeSettingsConstsImport } from "./routes/fee-settings/fee-settings.consts";
import { Route as FeeSettingsIndexImport } from "./routes/fee-settings/index";
import { Route as IndexImport } from "./routes/index";
import { Route as KycLimitsIndexImport } from "./routes/kyc-limits/index";
import { Route as LevelsIndexImport } from "./routes/levels/index";
import { Route as MainIndexImport } from "./routes/main/index";
import { Route as MarketCategoriesIndexImport } from "./routes/market-categories/index";
import { Route as MarketDataFeedsIndexImport } from "./routes/market-data-feeds/index";
import { Route as NetworksIndexImport } from "./routes/networks/index";
import { Route as NodesIndexImport } from "./routes/nodes/index";
import { Route as OrderHistoryIndexImport } from "./routes/order-history/index";
import { Route as OrgLevelsIndexImport } from "./routes/org-levels/index";
import { Route as PaymentHistoryIndexImport } from "./routes/payment-history/index";
import { Route as PermissionSectionsIndexImport } from "./routes/permission-sections/index";
import { Route as PermissionsIndexImport } from "./routes/permissions/index";
import { Route as ProductsIndexImport } from "./routes/products/index";
import { Route as ProfileIndexImport } from "./routes/profile/index";
import { Route as RecoverPasswordIndexImport } from "./routes/recover-password/index";
import { Route as ReferralDetailsIndexImport } from "./routes/referral-details/index";
import { Route as ReferralDetailsReferralDetailsRouteConstsImport } from "./routes/referral-details/referral-details-route.consts";
import { Route as ReferralIndexImport } from "./routes/referral/index";
import { Route as ReferralReferralRouteConstsImport } from "./routes/referral/referral-route.consts";
import { Route as RegionsIndexImport } from "./routes/regions/index";
import { Route as ResetPasswordIndexImport } from "./routes/reset-password/index";
import { Route as RoleIndexImport } from "./routes/role/index";
import { Route as RolesIndexImport } from "./routes/roles/index";
import { Route as RouterImport } from "./routes/router";
import { Route as ScannersIndexImport } from "./routes/scanners/index";
import { Route as SetPasswordIndexImport } from "./routes/set-password/index";
import { Route as SignInIndexImport } from "./routes/sign-in/index";
import { Route as SmsProvidersIndexImport } from "./routes/sms-providers/index";
import { Route as SpotTradingPairsIndexImport } from "./routes/spot-trading-pairs/index";
import { Route as TradingFeesIndexImport } from "./routes/trading-fees/index";
import { Route as TradingHistoryIndexImport } from "./routes/trading-history/index";
import { Route as VaultsIndexImport } from "./routes/vaults/index";
import { Route as WithdrawalDepositSettingsIndexImport } from "./routes/withdrawal-deposit-settings/index";

// Create/Update Routes

const RouterRoute = RouterImport.update({
  id: "/router",
  path: "/router",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const WithdrawalDepositSettingsIndexRoute = WithdrawalDepositSettingsIndexImport.update({
  id: "/withdrawal-deposit-settings/",
  path: "/withdrawal-deposit-settings/",
  getParentRoute: () => rootRoute,
} as any);

const VaultsIndexRoute = VaultsIndexImport.update({
  id: "/vaults/",
  path: "/vaults/",
  getParentRoute: () => rootRoute,
} as any);

const TradingHistoryIndexRoute = TradingHistoryIndexImport.update({
  id: "/trading-history/",
  path: "/trading-history/",
  getParentRoute: () => rootRoute,
} as any);

const TradingFeesIndexRoute = TradingFeesIndexImport.update({
  id: "/trading-fees/",
  path: "/trading-fees/",
  getParentRoute: () => rootRoute,
} as any);

const SpotTradingPairsIndexRoute = SpotTradingPairsIndexImport.update({
  id: "/spot-trading-pairs/",
  path: "/spot-trading-pairs/",
  getParentRoute: () => rootRoute,
} as any);

const SmsProvidersIndexRoute = SmsProvidersIndexImport.update({
  id: "/sms-providers/",
  path: "/sms-providers/",
  getParentRoute: () => rootRoute,
} as any);

const SignInIndexRoute = SignInIndexImport.update({
  id: "/sign-in/",
  path: "/sign-in/",
  getParentRoute: () => rootRoute,
} as any);

const SetPasswordIndexRoute = SetPasswordIndexImport.update({
  id: "/set-password/",
  path: "/set-password/",
  getParentRoute: () => rootRoute,
} as any);

const ScannersIndexRoute = ScannersIndexImport.update({
  id: "/scanners/",
  path: "/scanners/",
  getParentRoute: () => rootRoute,
} as any);

const RolesIndexRoute = RolesIndexImport.update({
  id: "/roles/",
  path: "/roles/",
  getParentRoute: () => rootRoute,
} as any);

const RoleIndexRoute = RoleIndexImport.update({
  id: "/role/",
  path: "/role/",
  getParentRoute: () => rootRoute,
} as any);

const ResetPasswordIndexRoute = ResetPasswordIndexImport.update({
  id: "/reset-password/",
  path: "/reset-password/",
  getParentRoute: () => rootRoute,
} as any);

const RegionsIndexRoute = RegionsIndexImport.update({
  id: "/regions/",
  path: "/regions/",
  getParentRoute: () => rootRoute,
} as any);

const ReferralIndexRoute = ReferralIndexImport.update({
  id: "/referral/",
  path: "/referral/",
  getParentRoute: () => rootRoute,
} as any);

const ReferralDetailsIndexRoute = ReferralDetailsIndexImport.update({
  id: "/referral-details/",
  path: "/referral-details/",
  getParentRoute: () => rootRoute,
} as any);

const RecoverPasswordIndexRoute = RecoverPasswordIndexImport.update({
  id: "/recover-password/",
  path: "/recover-password/",
  getParentRoute: () => rootRoute,
} as any);

const ProfileIndexRoute = ProfileIndexImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRoute,
} as any);

const ProductsIndexRoute = ProductsIndexImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => rootRoute,
} as any);

const PermissionsIndexRoute = PermissionsIndexImport.update({
  id: "/permissions/",
  path: "/permissions/",
  getParentRoute: () => rootRoute,
} as any);

const PermissionSectionsIndexRoute = PermissionSectionsIndexImport.update({
  id: "/permission-sections/",
  path: "/permission-sections/",
  getParentRoute: () => rootRoute,
} as any);

const PaymentHistoryIndexRoute = PaymentHistoryIndexImport.update({
  id: "/payment-history/",
  path: "/payment-history/",
  getParentRoute: () => rootRoute,
} as any);

const OrgLevelsIndexRoute = OrgLevelsIndexImport.update({
  id: "/org-levels/",
  path: "/org-levels/",
  getParentRoute: () => rootRoute,
} as any);

const OrderHistoryIndexRoute = OrderHistoryIndexImport.update({
  id: "/order-history/",
  path: "/order-history/",
  getParentRoute: () => rootRoute,
} as any);

const NodesIndexRoute = NodesIndexImport.update({
  id: "/nodes/",
  path: "/nodes/",
  getParentRoute: () => rootRoute,
} as any);

const NetworksIndexRoute = NetworksIndexImport.update({
  id: "/networks/",
  path: "/networks/",
  getParentRoute: () => rootRoute,
} as any);

const MarketDataFeedsIndexRoute = MarketDataFeedsIndexImport.update({
  id: "/market-data-feeds/",
  path: "/market-data-feeds/",
  getParentRoute: () => rootRoute,
} as any);

const MarketCategoriesIndexRoute = MarketCategoriesIndexImport.update({
  id: "/market-categories/",
  path: "/market-categories/",
  getParentRoute: () => rootRoute,
} as any);

const MainIndexRoute = MainIndexImport.update({
  id: "/main/",
  path: "/main/",
  getParentRoute: () => rootRoute,
} as any);

const LevelsIndexRoute = LevelsIndexImport.update({
  id: "/levels/",
  path: "/levels/",
  getParentRoute: () => rootRoute,
} as any);

const KycLimitsIndexRoute = KycLimitsIndexImport.update({
  id: "/kyc-limits/",
  path: "/kyc-limits/",
  getParentRoute: () => rootRoute,
} as any);

const FeeSettingsIndexRoute = FeeSettingsIndexImport.update({
  id: "/fee-settings/",
  path: "/fee-settings/",
  getParentRoute: () => rootRoute,
} as any);

const DepositsWithdrawalsIndexRoute = DepositsWithdrawalsIndexImport.update({
  id: "/deposits-withdrawals/",
  path: "/deposits-withdrawals/",
  getParentRoute: () => rootRoute,
} as any);

const DepositWithdrawalDetailsIndexRoute = DepositWithdrawalDetailsIndexImport.update({
  id: "/deposit-withdrawal-details/",
  path: "/deposit-withdrawal-details/",
  getParentRoute: () => rootRoute,
} as any);

const CustomersIndexRoute = CustomersIndexImport.update({
  id: "/customers/",
  path: "/customers/",
  getParentRoute: () => rootRoute,
} as any);

const CustomerProfileIndexRoute = CustomerProfileIndexImport.update({
  id: "/customer-profile/",
  path: "/customer-profile/",
  getParentRoute: () => rootRoute,
} as any);

const CustomerDepositWithdrawalDetailsIndexRoute = CustomerDepositWithdrawalDetailsIndexImport.update({
  id: "/customer-deposit-withdrawal-details/",
  path: "/customer-deposit-withdrawal-details/",
  getParentRoute: () => rootRoute,
} as any);

const CoinsIndexRoute = CoinsIndexImport.update({
  id: "/coins/",
  path: "/coins/",
  getParentRoute: () => rootRoute,
} as any);

const CheckEmailIndexRoute = CheckEmailIndexImport.update({
  id: "/check-email/",
  path: "/check-email/",
  getParentRoute: () => rootRoute,
} as any);

const BrandsIndexRoute = BrandsIndexImport.update({
  id: "/brands/",
  path: "/brands/",
  getParentRoute: () => rootRoute,
} as any);

const AuthIndexRoute = AuthIndexImport.update({
  id: "/auth/",
  path: "/auth/",
  getParentRoute: () => rootRoute,
} as any);

const AssetsIndexRoute = AssetsIndexImport.update({
  id: "/assets/",
  path: "/assets/",
  getParentRoute: () => rootRoute,
} as any);

const ApiKeysIndexRoute = ApiKeysIndexImport.update({
  id: "/api-keys/",
  path: "/api-keys/",
  getParentRoute: () => rootRoute,
} as any);

const ApiKeyDetailsIndexRoute = ApiKeyDetailsIndexImport.update({
  id: "/api-key-details/",
  path: "/api-key-details/",
  getParentRoute: () => rootRoute,
} as any);

const AdminUsersIndexRoute = AdminUsersIndexImport.update({
  id: "/admin-users/",
  path: "/admin-users/",
  getParentRoute: () => rootRoute,
} as any);

const AdminUserIndexRoute = AdminUserIndexImport.update({
  id: "/admin-user/",
  path: "/admin-user/",
  getParentRoute: () => rootRoute,
} as any);

const AccountsIndexRoute = AccountsIndexImport.update({
  id: "/accounts/",
  path: "/accounts/",
  getParentRoute: () => rootRoute,
} as any);

const AccountDetailsIndexRoute = AccountDetailsIndexImport.update({
  id: "/account-details/",
  path: "/account-details/",
  getParentRoute: () => rootRoute,
} as any);

const ReferralReferralRouteConstsRoute = ReferralReferralRouteConstsImport.update({
  id: "/referral/referral-route/consts",
  path: "/referral/referral-route/consts",
  getParentRoute: () => rootRoute,
} as any);

const ReferralDetailsReferralDetailsRouteConstsRoute = ReferralDetailsReferralDetailsRouteConstsImport.update({
  id: "/referral-details/referral-details-route/consts",
  path: "/referral-details/referral-details-route/consts",
  getParentRoute: () => rootRoute,
} as any);

const FeeSettingsFeeSettingsConstsRoute = FeeSettingsFeeSettingsConstsImport.update({
  id: "/fee-settings/fee-settings/consts",
  path: "/fee-settings/fee-settings/consts",
  getParentRoute: () => rootRoute,
} as any);

const DepositsWithdrawalsDepositWithdrawalsConstsRoute = DepositsWithdrawalsDepositWithdrawalsConstsImport.update({
  id: "/deposits-withdrawals/deposit-withdrawals/consts",
  path: "/deposits-withdrawals/deposit-withdrawals/consts",
  getParentRoute: () => rootRoute,
} as any);

const CustomerProfileCustomerProfileRouteConstsRoute = CustomerProfileCustomerProfileRouteConstsImport.update({
  id: "/customer-profile/customer-profile-route/consts",
  path: "/customer-profile/customer-profile-route/consts",
  getParentRoute: () => rootRoute,
} as any);

const ApiKeyDetailsApiKeyDetailsConstsRoute = ApiKeyDetailsApiKeyDetailsConstsImport.update({
  id: "/api-key-details/api-key-details/consts",
  path: "/api-key-details/api-key-details/consts",
  getParentRoute: () => rootRoute,
} as any);

const AccountDetailsAccountDetailsConstsRoute = AccountDetailsAccountDetailsConstsImport.update({
  id: "/account-details/account-details/consts",
  path: "/account-details/account-details/consts",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/router": {
      id: "/router";
      path: "/router";
      fullPath: "/router";
      preLoaderRoute: typeof RouterImport;
      parentRoute: typeof rootRoute;
    };
    "/account-details/": {
      id: "/account-details/";
      path: "/account-details";
      fullPath: "/account-details";
      preLoaderRoute: typeof AccountDetailsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/accounts/": {
      id: "/accounts/";
      path: "/accounts";
      fullPath: "/accounts";
      preLoaderRoute: typeof AccountsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/admin-user/": {
      id: "/admin-user/";
      path: "/admin-user";
      fullPath: "/admin-user";
      preLoaderRoute: typeof AdminUserIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/admin-users/": {
      id: "/admin-users/";
      path: "/admin-users";
      fullPath: "/admin-users";
      preLoaderRoute: typeof AdminUsersIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/api-key-details/": {
      id: "/api-key-details/";
      path: "/api-key-details";
      fullPath: "/api-key-details";
      preLoaderRoute: typeof ApiKeyDetailsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/api-keys/": {
      id: "/api-keys/";
      path: "/api-keys";
      fullPath: "/api-keys";
      preLoaderRoute: typeof ApiKeysIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/assets/": {
      id: "/assets/";
      path: "/assets";
      fullPath: "/assets";
      preLoaderRoute: typeof AssetsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/": {
      id: "/auth/";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof AuthIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/brands/": {
      id: "/brands/";
      path: "/brands";
      fullPath: "/brands";
      preLoaderRoute: typeof BrandsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/check-email/": {
      id: "/check-email/";
      path: "/check-email";
      fullPath: "/check-email";
      preLoaderRoute: typeof CheckEmailIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/coins/": {
      id: "/coins/";
      path: "/coins";
      fullPath: "/coins";
      preLoaderRoute: typeof CoinsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/customer-deposit-withdrawal-details/": {
      id: "/customer-deposit-withdrawal-details/";
      path: "/customer-deposit-withdrawal-details";
      fullPath: "/customer-deposit-withdrawal-details";
      preLoaderRoute: typeof CustomerDepositWithdrawalDetailsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/customer-profile/": {
      id: "/customer-profile/";
      path: "/customer-profile";
      fullPath: "/customer-profile";
      preLoaderRoute: typeof CustomerProfileIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/customers/": {
      id: "/customers/";
      path: "/customers";
      fullPath: "/customers";
      preLoaderRoute: typeof CustomersIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/deposit-withdrawal-details/": {
      id: "/deposit-withdrawal-details/";
      path: "/deposit-withdrawal-details";
      fullPath: "/deposit-withdrawal-details";
      preLoaderRoute: typeof DepositWithdrawalDetailsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/deposits-withdrawals/": {
      id: "/deposits-withdrawals/";
      path: "/deposits-withdrawals";
      fullPath: "/deposits-withdrawals";
      preLoaderRoute: typeof DepositsWithdrawalsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/fee-settings/": {
      id: "/fee-settings/";
      path: "/fee-settings";
      fullPath: "/fee-settings";
      preLoaderRoute: typeof FeeSettingsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/kyc-limits/": {
      id: "/kyc-limits/";
      path: "/kyc-limits";
      fullPath: "/kyc-limits";
      preLoaderRoute: typeof KycLimitsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/levels/": {
      id: "/levels/";
      path: "/levels";
      fullPath: "/levels";
      preLoaderRoute: typeof LevelsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/main/": {
      id: "/main/";
      path: "/main";
      fullPath: "/main";
      preLoaderRoute: typeof MainIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/market-categories/": {
      id: "/market-categories/";
      path: "/market-categories";
      fullPath: "/market-categories";
      preLoaderRoute: typeof MarketCategoriesIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/market-data-feeds/": {
      id: "/market-data-feeds/";
      path: "/market-data-feeds";
      fullPath: "/market-data-feeds";
      preLoaderRoute: typeof MarketDataFeedsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/networks/": {
      id: "/networks/";
      path: "/networks";
      fullPath: "/networks";
      preLoaderRoute: typeof NetworksIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/nodes/": {
      id: "/nodes/";
      path: "/nodes";
      fullPath: "/nodes";
      preLoaderRoute: typeof NodesIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/order-history/": {
      id: "/order-history/";
      path: "/order-history";
      fullPath: "/order-history";
      preLoaderRoute: typeof OrderHistoryIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/org-levels/": {
      id: "/org-levels/";
      path: "/org-levels";
      fullPath: "/org-levels";
      preLoaderRoute: typeof OrgLevelsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/payment-history/": {
      id: "/payment-history/";
      path: "/payment-history";
      fullPath: "/payment-history";
      preLoaderRoute: typeof PaymentHistoryIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/permission-sections/": {
      id: "/permission-sections/";
      path: "/permission-sections";
      fullPath: "/permission-sections";
      preLoaderRoute: typeof PermissionSectionsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/permissions/": {
      id: "/permissions/";
      path: "/permissions";
      fullPath: "/permissions";
      preLoaderRoute: typeof PermissionsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/products/": {
      id: "/products/";
      path: "/products";
      fullPath: "/products";
      preLoaderRoute: typeof ProductsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/profile/": {
      id: "/profile/";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/recover-password/": {
      id: "/recover-password/";
      path: "/recover-password";
      fullPath: "/recover-password";
      preLoaderRoute: typeof RecoverPasswordIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/referral-details/": {
      id: "/referral-details/";
      path: "/referral-details";
      fullPath: "/referral-details";
      preLoaderRoute: typeof ReferralDetailsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/referral/": {
      id: "/referral/";
      path: "/referral";
      fullPath: "/referral";
      preLoaderRoute: typeof ReferralIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/regions/": {
      id: "/regions/";
      path: "/regions";
      fullPath: "/regions";
      preLoaderRoute: typeof RegionsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/reset-password/": {
      id: "/reset-password/";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/role/": {
      id: "/role/";
      path: "/role";
      fullPath: "/role";
      preLoaderRoute: typeof RoleIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/roles/": {
      id: "/roles/";
      path: "/roles";
      fullPath: "/roles";
      preLoaderRoute: typeof RolesIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/scanners/": {
      id: "/scanners/";
      path: "/scanners";
      fullPath: "/scanners";
      preLoaderRoute: typeof ScannersIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/set-password/": {
      id: "/set-password/";
      path: "/set-password";
      fullPath: "/set-password";
      preLoaderRoute: typeof SetPasswordIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/sign-in/": {
      id: "/sign-in/";
      path: "/sign-in";
      fullPath: "/sign-in";
      preLoaderRoute: typeof SignInIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/sms-providers/": {
      id: "/sms-providers/";
      path: "/sms-providers";
      fullPath: "/sms-providers";
      preLoaderRoute: typeof SmsProvidersIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/spot-trading-pairs/": {
      id: "/spot-trading-pairs/";
      path: "/spot-trading-pairs";
      fullPath: "/spot-trading-pairs";
      preLoaderRoute: typeof SpotTradingPairsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/trading-fees/": {
      id: "/trading-fees/";
      path: "/trading-fees";
      fullPath: "/trading-fees";
      preLoaderRoute: typeof TradingFeesIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/trading-history/": {
      id: "/trading-history/";
      path: "/trading-history";
      fullPath: "/trading-history";
      preLoaderRoute: typeof TradingHistoryIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/vaults/": {
      id: "/vaults/";
      path: "/vaults";
      fullPath: "/vaults";
      preLoaderRoute: typeof VaultsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/withdrawal-deposit-settings/": {
      id: "/withdrawal-deposit-settings/";
      path: "/withdrawal-deposit-settings";
      fullPath: "/withdrawal-deposit-settings";
      preLoaderRoute: typeof WithdrawalDepositSettingsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/account-details/account-details/consts": {
      id: "/account-details/account-details/consts";
      path: "/account-details/account-details/consts";
      fullPath: "/account-details/account-details/consts";
      preLoaderRoute: typeof AccountDetailsAccountDetailsConstsImport;
      parentRoute: typeof rootRoute;
    };
    "/api-key-details/api-key-details/consts": {
      id: "/api-key-details/api-key-details/consts";
      path: "/api-key-details/api-key-details/consts";
      fullPath: "/api-key-details/api-key-details/consts";
      preLoaderRoute: typeof ApiKeyDetailsApiKeyDetailsConstsImport;
      parentRoute: typeof rootRoute;
    };
    "/customer-profile/customer-profile-route/consts": {
      id: "/customer-profile/customer-profile-route/consts";
      path: "/customer-profile/customer-profile-route/consts";
      fullPath: "/customer-profile/customer-profile-route/consts";
      preLoaderRoute: typeof CustomerProfileCustomerProfileRouteConstsImport;
      parentRoute: typeof rootRoute;
    };
    "/deposits-withdrawals/deposit-withdrawals/consts": {
      id: "/deposits-withdrawals/deposit-withdrawals/consts";
      path: "/deposits-withdrawals/deposit-withdrawals/consts";
      fullPath: "/deposits-withdrawals/deposit-withdrawals/consts";
      preLoaderRoute: typeof DepositsWithdrawalsDepositWithdrawalsConstsImport;
      parentRoute: typeof rootRoute;
    };
    "/fee-settings/fee-settings/consts": {
      id: "/fee-settings/fee-settings/consts";
      path: "/fee-settings/fee-settings/consts";
      fullPath: "/fee-settings/fee-settings/consts";
      preLoaderRoute: typeof FeeSettingsFeeSettingsConstsImport;
      parentRoute: typeof rootRoute;
    };
    "/referral-details/referral-details-route/consts": {
      id: "/referral-details/referral-details-route/consts";
      path: "/referral-details/referral-details-route/consts";
      fullPath: "/referral-details/referral-details-route/consts";
      preLoaderRoute: typeof ReferralDetailsReferralDetailsRouteConstsImport;
      parentRoute: typeof rootRoute;
    };
    "/referral/referral-route/consts": {
      id: "/referral/referral-route/consts";
      path: "/referral/referral-route/consts";
      fullPath: "/referral/referral-route/consts";
      preLoaderRoute: typeof ReferralReferralRouteConstsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/router": typeof RouterRoute;
  "/account-details": typeof AccountDetailsIndexRoute;
  "/accounts": typeof AccountsIndexRoute;
  "/admin-user": typeof AdminUserIndexRoute;
  "/admin-users": typeof AdminUsersIndexRoute;
  "/api-key-details": typeof ApiKeyDetailsIndexRoute;
  "/api-keys": typeof ApiKeysIndexRoute;
  "/assets": typeof AssetsIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/brands": typeof BrandsIndexRoute;
  "/check-email": typeof CheckEmailIndexRoute;
  "/coins": typeof CoinsIndexRoute;
  "/customer-deposit-withdrawal-details": typeof CustomerDepositWithdrawalDetailsIndexRoute;
  "/customer-profile": typeof CustomerProfileIndexRoute;
  "/customers": typeof CustomersIndexRoute;
  "/deposit-withdrawal-details": typeof DepositWithdrawalDetailsIndexRoute;
  "/deposits-withdrawals": typeof DepositsWithdrawalsIndexRoute;
  "/fee-settings": typeof FeeSettingsIndexRoute;
  "/kyc-limits": typeof KycLimitsIndexRoute;
  "/levels": typeof LevelsIndexRoute;
  "/main": typeof MainIndexRoute;
  "/market-categories": typeof MarketCategoriesIndexRoute;
  "/market-data-feeds": typeof MarketDataFeedsIndexRoute;
  "/networks": typeof NetworksIndexRoute;
  "/nodes": typeof NodesIndexRoute;
  "/order-history": typeof OrderHistoryIndexRoute;
  "/org-levels": typeof OrgLevelsIndexRoute;
  "/payment-history": typeof PaymentHistoryIndexRoute;
  "/permission-sections": typeof PermissionSectionsIndexRoute;
  "/permissions": typeof PermissionsIndexRoute;
  "/products": typeof ProductsIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/recover-password": typeof RecoverPasswordIndexRoute;
  "/referral-details": typeof ReferralDetailsIndexRoute;
  "/referral": typeof ReferralIndexRoute;
  "/regions": typeof RegionsIndexRoute;
  "/reset-password": typeof ResetPasswordIndexRoute;
  "/role": typeof RoleIndexRoute;
  "/roles": typeof RolesIndexRoute;
  "/scanners": typeof ScannersIndexRoute;
  "/set-password": typeof SetPasswordIndexRoute;
  "/sign-in": typeof SignInIndexRoute;
  "/sms-providers": typeof SmsProvidersIndexRoute;
  "/spot-trading-pairs": typeof SpotTradingPairsIndexRoute;
  "/trading-fees": typeof TradingFeesIndexRoute;
  "/trading-history": typeof TradingHistoryIndexRoute;
  "/vaults": typeof VaultsIndexRoute;
  "/withdrawal-deposit-settings": typeof WithdrawalDepositSettingsIndexRoute;
  "/account-details/account-details/consts": typeof AccountDetailsAccountDetailsConstsRoute;
  "/api-key-details/api-key-details/consts": typeof ApiKeyDetailsApiKeyDetailsConstsRoute;
  "/customer-profile/customer-profile-route/consts": typeof CustomerProfileCustomerProfileRouteConstsRoute;
  "/deposits-withdrawals/deposit-withdrawals/consts": typeof DepositsWithdrawalsDepositWithdrawalsConstsRoute;
  "/fee-settings/fee-settings/consts": typeof FeeSettingsFeeSettingsConstsRoute;
  "/referral-details/referral-details-route/consts": typeof ReferralDetailsReferralDetailsRouteConstsRoute;
  "/referral/referral-route/consts": typeof ReferralReferralRouteConstsRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/router": typeof RouterRoute;
  "/account-details": typeof AccountDetailsIndexRoute;
  "/accounts": typeof AccountsIndexRoute;
  "/admin-user": typeof AdminUserIndexRoute;
  "/admin-users": typeof AdminUsersIndexRoute;
  "/api-key-details": typeof ApiKeyDetailsIndexRoute;
  "/api-keys": typeof ApiKeysIndexRoute;
  "/assets": typeof AssetsIndexRoute;
  "/auth": typeof AuthIndexRoute;
  "/brands": typeof BrandsIndexRoute;
  "/check-email": typeof CheckEmailIndexRoute;
  "/coins": typeof CoinsIndexRoute;
  "/customer-deposit-withdrawal-details": typeof CustomerDepositWithdrawalDetailsIndexRoute;
  "/customer-profile": typeof CustomerProfileIndexRoute;
  "/customers": typeof CustomersIndexRoute;
  "/deposit-withdrawal-details": typeof DepositWithdrawalDetailsIndexRoute;
  "/deposits-withdrawals": typeof DepositsWithdrawalsIndexRoute;
  "/fee-settings": typeof FeeSettingsIndexRoute;
  "/kyc-limits": typeof KycLimitsIndexRoute;
  "/levels": typeof LevelsIndexRoute;
  "/main": typeof MainIndexRoute;
  "/market-categories": typeof MarketCategoriesIndexRoute;
  "/market-data-feeds": typeof MarketDataFeedsIndexRoute;
  "/networks": typeof NetworksIndexRoute;
  "/nodes": typeof NodesIndexRoute;
  "/order-history": typeof OrderHistoryIndexRoute;
  "/org-levels": typeof OrgLevelsIndexRoute;
  "/payment-history": typeof PaymentHistoryIndexRoute;
  "/permission-sections": typeof PermissionSectionsIndexRoute;
  "/permissions": typeof PermissionsIndexRoute;
  "/products": typeof ProductsIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/recover-password": typeof RecoverPasswordIndexRoute;
  "/referral-details": typeof ReferralDetailsIndexRoute;
  "/referral": typeof ReferralIndexRoute;
  "/regions": typeof RegionsIndexRoute;
  "/reset-password": typeof ResetPasswordIndexRoute;
  "/role": typeof RoleIndexRoute;
  "/roles": typeof RolesIndexRoute;
  "/scanners": typeof ScannersIndexRoute;
  "/set-password": typeof SetPasswordIndexRoute;
  "/sign-in": typeof SignInIndexRoute;
  "/sms-providers": typeof SmsProvidersIndexRoute;
  "/spot-trading-pairs": typeof SpotTradingPairsIndexRoute;
  "/trading-fees": typeof TradingFeesIndexRoute;
  "/trading-history": typeof TradingHistoryIndexRoute;
  "/vaults": typeof VaultsIndexRoute;
  "/withdrawal-deposit-settings": typeof WithdrawalDepositSettingsIndexRoute;
  "/account-details/account-details/consts": typeof AccountDetailsAccountDetailsConstsRoute;
  "/api-key-details/api-key-details/consts": typeof ApiKeyDetailsApiKeyDetailsConstsRoute;
  "/customer-profile/customer-profile-route/consts": typeof CustomerProfileCustomerProfileRouteConstsRoute;
  "/deposits-withdrawals/deposit-withdrawals/consts": typeof DepositsWithdrawalsDepositWithdrawalsConstsRoute;
  "/fee-settings/fee-settings/consts": typeof FeeSettingsFeeSettingsConstsRoute;
  "/referral-details/referral-details-route/consts": typeof ReferralDetailsReferralDetailsRouteConstsRoute;
  "/referral/referral-route/consts": typeof ReferralReferralRouteConstsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/router": typeof RouterRoute;
  "/account-details/": typeof AccountDetailsIndexRoute;
  "/accounts/": typeof AccountsIndexRoute;
  "/admin-user/": typeof AdminUserIndexRoute;
  "/admin-users/": typeof AdminUsersIndexRoute;
  "/api-key-details/": typeof ApiKeyDetailsIndexRoute;
  "/api-keys/": typeof ApiKeysIndexRoute;
  "/assets/": typeof AssetsIndexRoute;
  "/auth/": typeof AuthIndexRoute;
  "/brands/": typeof BrandsIndexRoute;
  "/check-email/": typeof CheckEmailIndexRoute;
  "/coins/": typeof CoinsIndexRoute;
  "/customer-deposit-withdrawal-details/": typeof CustomerDepositWithdrawalDetailsIndexRoute;
  "/customer-profile/": typeof CustomerProfileIndexRoute;
  "/customers/": typeof CustomersIndexRoute;
  "/deposit-withdrawal-details/": typeof DepositWithdrawalDetailsIndexRoute;
  "/deposits-withdrawals/": typeof DepositsWithdrawalsIndexRoute;
  "/fee-settings/": typeof FeeSettingsIndexRoute;
  "/kyc-limits/": typeof KycLimitsIndexRoute;
  "/levels/": typeof LevelsIndexRoute;
  "/main/": typeof MainIndexRoute;
  "/market-categories/": typeof MarketCategoriesIndexRoute;
  "/market-data-feeds/": typeof MarketDataFeedsIndexRoute;
  "/networks/": typeof NetworksIndexRoute;
  "/nodes/": typeof NodesIndexRoute;
  "/order-history/": typeof OrderHistoryIndexRoute;
  "/org-levels/": typeof OrgLevelsIndexRoute;
  "/payment-history/": typeof PaymentHistoryIndexRoute;
  "/permission-sections/": typeof PermissionSectionsIndexRoute;
  "/permissions/": typeof PermissionsIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/recover-password/": typeof RecoverPasswordIndexRoute;
  "/referral-details/": typeof ReferralDetailsIndexRoute;
  "/referral/": typeof ReferralIndexRoute;
  "/regions/": typeof RegionsIndexRoute;
  "/reset-password/": typeof ResetPasswordIndexRoute;
  "/role/": typeof RoleIndexRoute;
  "/roles/": typeof RolesIndexRoute;
  "/scanners/": typeof ScannersIndexRoute;
  "/set-password/": typeof SetPasswordIndexRoute;
  "/sign-in/": typeof SignInIndexRoute;
  "/sms-providers/": typeof SmsProvidersIndexRoute;
  "/spot-trading-pairs/": typeof SpotTradingPairsIndexRoute;
  "/trading-fees/": typeof TradingFeesIndexRoute;
  "/trading-history/": typeof TradingHistoryIndexRoute;
  "/vaults/": typeof VaultsIndexRoute;
  "/withdrawal-deposit-settings/": typeof WithdrawalDepositSettingsIndexRoute;
  "/account-details/account-details/consts": typeof AccountDetailsAccountDetailsConstsRoute;
  "/api-key-details/api-key-details/consts": typeof ApiKeyDetailsApiKeyDetailsConstsRoute;
  "/customer-profile/customer-profile-route/consts": typeof CustomerProfileCustomerProfileRouteConstsRoute;
  "/deposits-withdrawals/deposit-withdrawals/consts": typeof DepositsWithdrawalsDepositWithdrawalsConstsRoute;
  "/fee-settings/fee-settings/consts": typeof FeeSettingsFeeSettingsConstsRoute;
  "/referral-details/referral-details-route/consts": typeof ReferralDetailsReferralDetailsRouteConstsRoute;
  "/referral/referral-route/consts": typeof ReferralReferralRouteConstsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/router"
    | "/account-details"
    | "/accounts"
    | "/admin-user"
    | "/admin-users"
    | "/api-key-details"
    | "/api-keys"
    | "/assets"
    | "/auth"
    | "/brands"
    | "/check-email"
    | "/coins"
    | "/customer-deposit-withdrawal-details"
    | "/customer-profile"
    | "/customers"
    | "/deposit-withdrawal-details"
    | "/deposits-withdrawals"
    | "/fee-settings"
    | "/kyc-limits"
    | "/levels"
    | "/main"
    | "/market-categories"
    | "/market-data-feeds"
    | "/networks"
    | "/nodes"
    | "/order-history"
    | "/org-levels"
    | "/payment-history"
    | "/permission-sections"
    | "/permissions"
    | "/products"
    | "/profile"
    | "/recover-password"
    | "/referral-details"
    | "/referral"
    | "/regions"
    | "/reset-password"
    | "/role"
    | "/roles"
    | "/scanners"
    | "/set-password"
    | "/sign-in"
    | "/sms-providers"
    | "/spot-trading-pairs"
    | "/trading-fees"
    | "/trading-history"
    | "/vaults"
    | "/withdrawal-deposit-settings"
    | "/account-details/account-details/consts"
    | "/api-key-details/api-key-details/consts"
    | "/customer-profile/customer-profile-route/consts"
    | "/deposits-withdrawals/deposit-withdrawals/consts"
    | "/fee-settings/fee-settings/consts"
    | "/referral-details/referral-details-route/consts"
    | "/referral/referral-route/consts";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/router"
    | "/account-details"
    | "/accounts"
    | "/admin-user"
    | "/admin-users"
    | "/api-key-details"
    | "/api-keys"
    | "/assets"
    | "/auth"
    | "/brands"
    | "/check-email"
    | "/coins"
    | "/customer-deposit-withdrawal-details"
    | "/customer-profile"
    | "/customers"
    | "/deposit-withdrawal-details"
    | "/deposits-withdrawals"
    | "/fee-settings"
    | "/kyc-limits"
    | "/levels"
    | "/main"
    | "/market-categories"
    | "/market-data-feeds"
    | "/networks"
    | "/nodes"
    | "/order-history"
    | "/org-levels"
    | "/payment-history"
    | "/permission-sections"
    | "/permissions"
    | "/products"
    | "/profile"
    | "/recover-password"
    | "/referral-details"
    | "/referral"
    | "/regions"
    | "/reset-password"
    | "/role"
    | "/roles"
    | "/scanners"
    | "/set-password"
    | "/sign-in"
    | "/sms-providers"
    | "/spot-trading-pairs"
    | "/trading-fees"
    | "/trading-history"
    | "/vaults"
    | "/withdrawal-deposit-settings"
    | "/account-details/account-details/consts"
    | "/api-key-details/api-key-details/consts"
    | "/customer-profile/customer-profile-route/consts"
    | "/deposits-withdrawals/deposit-withdrawals/consts"
    | "/fee-settings/fee-settings/consts"
    | "/referral-details/referral-details-route/consts"
    | "/referral/referral-route/consts";
  id:
    | "__root__"
    | "/"
    | "/router"
    | "/account-details/"
    | "/accounts/"
    | "/admin-user/"
    | "/admin-users/"
    | "/api-key-details/"
    | "/api-keys/"
    | "/assets/"
    | "/auth/"
    | "/brands/"
    | "/check-email/"
    | "/coins/"
    | "/customer-deposit-withdrawal-details/"
    | "/customer-profile/"
    | "/customers/"
    | "/deposit-withdrawal-details/"
    | "/deposits-withdrawals/"
    | "/fee-settings/"
    | "/kyc-limits/"
    | "/levels/"
    | "/main/"
    | "/market-categories/"
    | "/market-data-feeds/"
    | "/networks/"
    | "/nodes/"
    | "/order-history/"
    | "/org-levels/"
    | "/payment-history/"
    | "/permission-sections/"
    | "/permissions/"
    | "/products/"
    | "/profile/"
    | "/recover-password/"
    | "/referral-details/"
    | "/referral/"
    | "/regions/"
    | "/reset-password/"
    | "/role/"
    | "/roles/"
    | "/scanners/"
    | "/set-password/"
    | "/sign-in/"
    | "/sms-providers/"
    | "/spot-trading-pairs/"
    | "/trading-fees/"
    | "/trading-history/"
    | "/vaults/"
    | "/withdrawal-deposit-settings/"
    | "/account-details/account-details/consts"
    | "/api-key-details/api-key-details/consts"
    | "/customer-profile/customer-profile-route/consts"
    | "/deposits-withdrawals/deposit-withdrawals/consts"
    | "/fee-settings/fee-settings/consts"
    | "/referral-details/referral-details-route/consts"
    | "/referral/referral-route/consts";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  RouterRoute: typeof RouterRoute;
  AccountDetailsIndexRoute: typeof AccountDetailsIndexRoute;
  AccountsIndexRoute: typeof AccountsIndexRoute;
  AdminUserIndexRoute: typeof AdminUserIndexRoute;
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute;
  ApiKeyDetailsIndexRoute: typeof ApiKeyDetailsIndexRoute;
  ApiKeysIndexRoute: typeof ApiKeysIndexRoute;
  AssetsIndexRoute: typeof AssetsIndexRoute;
  AuthIndexRoute: typeof AuthIndexRoute;
  BrandsIndexRoute: typeof BrandsIndexRoute;
  CheckEmailIndexRoute: typeof CheckEmailIndexRoute;
  CoinsIndexRoute: typeof CoinsIndexRoute;
  CustomerDepositWithdrawalDetailsIndexRoute: typeof CustomerDepositWithdrawalDetailsIndexRoute;
  CustomerProfileIndexRoute: typeof CustomerProfileIndexRoute;
  CustomersIndexRoute: typeof CustomersIndexRoute;
  DepositWithdrawalDetailsIndexRoute: typeof DepositWithdrawalDetailsIndexRoute;
  DepositsWithdrawalsIndexRoute: typeof DepositsWithdrawalsIndexRoute;
  FeeSettingsIndexRoute: typeof FeeSettingsIndexRoute;
  KycLimitsIndexRoute: typeof KycLimitsIndexRoute;
  LevelsIndexRoute: typeof LevelsIndexRoute;
  MainIndexRoute: typeof MainIndexRoute;
  MarketCategoriesIndexRoute: typeof MarketCategoriesIndexRoute;
  MarketDataFeedsIndexRoute: typeof MarketDataFeedsIndexRoute;
  NetworksIndexRoute: typeof NetworksIndexRoute;
  NodesIndexRoute: typeof NodesIndexRoute;
  OrderHistoryIndexRoute: typeof OrderHistoryIndexRoute;
  OrgLevelsIndexRoute: typeof OrgLevelsIndexRoute;
  PaymentHistoryIndexRoute: typeof PaymentHistoryIndexRoute;
  PermissionSectionsIndexRoute: typeof PermissionSectionsIndexRoute;
  PermissionsIndexRoute: typeof PermissionsIndexRoute;
  ProductsIndexRoute: typeof ProductsIndexRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
  RecoverPasswordIndexRoute: typeof RecoverPasswordIndexRoute;
  ReferralDetailsIndexRoute: typeof ReferralDetailsIndexRoute;
  ReferralIndexRoute: typeof ReferralIndexRoute;
  RegionsIndexRoute: typeof RegionsIndexRoute;
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute;
  RoleIndexRoute: typeof RoleIndexRoute;
  RolesIndexRoute: typeof RolesIndexRoute;
  ScannersIndexRoute: typeof ScannersIndexRoute;
  SetPasswordIndexRoute: typeof SetPasswordIndexRoute;
  SignInIndexRoute: typeof SignInIndexRoute;
  SmsProvidersIndexRoute: typeof SmsProvidersIndexRoute;
  SpotTradingPairsIndexRoute: typeof SpotTradingPairsIndexRoute;
  TradingFeesIndexRoute: typeof TradingFeesIndexRoute;
  TradingHistoryIndexRoute: typeof TradingHistoryIndexRoute;
  VaultsIndexRoute: typeof VaultsIndexRoute;
  WithdrawalDepositSettingsIndexRoute: typeof WithdrawalDepositSettingsIndexRoute;
  AccountDetailsAccountDetailsConstsRoute: typeof AccountDetailsAccountDetailsConstsRoute;
  ApiKeyDetailsApiKeyDetailsConstsRoute: typeof ApiKeyDetailsApiKeyDetailsConstsRoute;
  CustomerProfileCustomerProfileRouteConstsRoute: typeof CustomerProfileCustomerProfileRouteConstsRoute;
  DepositsWithdrawalsDepositWithdrawalsConstsRoute: typeof DepositsWithdrawalsDepositWithdrawalsConstsRoute;
  FeeSettingsFeeSettingsConstsRoute: typeof FeeSettingsFeeSettingsConstsRoute;
  ReferralDetailsReferralDetailsRouteConstsRoute: typeof ReferralDetailsReferralDetailsRouteConstsRoute;
  ReferralReferralRouteConstsRoute: typeof ReferralReferralRouteConstsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RouterRoute: RouterRoute,
  AccountDetailsIndexRoute: AccountDetailsIndexRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AdminUserIndexRoute: AdminUserIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  ApiKeyDetailsIndexRoute: ApiKeyDetailsIndexRoute,
  ApiKeysIndexRoute: ApiKeysIndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  CheckEmailIndexRoute: CheckEmailIndexRoute,
  CoinsIndexRoute: CoinsIndexRoute,
  CustomerDepositWithdrawalDetailsIndexRoute: CustomerDepositWithdrawalDetailsIndexRoute,
  CustomerProfileIndexRoute: CustomerProfileIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  DepositWithdrawalDetailsIndexRoute: DepositWithdrawalDetailsIndexRoute,
  DepositsWithdrawalsIndexRoute: DepositsWithdrawalsIndexRoute,
  FeeSettingsIndexRoute: FeeSettingsIndexRoute,
  KycLimitsIndexRoute: KycLimitsIndexRoute,
  LevelsIndexRoute: LevelsIndexRoute,
  MainIndexRoute: MainIndexRoute,
  MarketCategoriesIndexRoute: MarketCategoriesIndexRoute,
  MarketDataFeedsIndexRoute: MarketDataFeedsIndexRoute,
  NetworksIndexRoute: NetworksIndexRoute,
  NodesIndexRoute: NodesIndexRoute,
  OrderHistoryIndexRoute: OrderHistoryIndexRoute,
  OrgLevelsIndexRoute: OrgLevelsIndexRoute,
  PaymentHistoryIndexRoute: PaymentHistoryIndexRoute,
  PermissionSectionsIndexRoute: PermissionSectionsIndexRoute,
  PermissionsIndexRoute: PermissionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RecoverPasswordIndexRoute: RecoverPasswordIndexRoute,
  ReferralDetailsIndexRoute: ReferralDetailsIndexRoute,
  ReferralIndexRoute: ReferralIndexRoute,
  RegionsIndexRoute: RegionsIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  RoleIndexRoute: RoleIndexRoute,
  RolesIndexRoute: RolesIndexRoute,
  ScannersIndexRoute: ScannersIndexRoute,
  SetPasswordIndexRoute: SetPasswordIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  SmsProvidersIndexRoute: SmsProvidersIndexRoute,
  SpotTradingPairsIndexRoute: SpotTradingPairsIndexRoute,
  TradingFeesIndexRoute: TradingFeesIndexRoute,
  TradingHistoryIndexRoute: TradingHistoryIndexRoute,
  VaultsIndexRoute: VaultsIndexRoute,
  WithdrawalDepositSettingsIndexRoute: WithdrawalDepositSettingsIndexRoute,
  AccountDetailsAccountDetailsConstsRoute: AccountDetailsAccountDetailsConstsRoute,
  ApiKeyDetailsApiKeyDetailsConstsRoute: ApiKeyDetailsApiKeyDetailsConstsRoute,
  CustomerProfileCustomerProfileRouteConstsRoute: CustomerProfileCustomerProfileRouteConstsRoute,
  DepositsWithdrawalsDepositWithdrawalsConstsRoute: DepositsWithdrawalsDepositWithdrawalsConstsRoute,
  FeeSettingsFeeSettingsConstsRoute: FeeSettingsFeeSettingsConstsRoute,
  ReferralDetailsReferralDetailsRouteConstsRoute: ReferralDetailsReferralDetailsRouteConstsRoute,
  ReferralReferralRouteConstsRoute: ReferralReferralRouteConstsRoute,
};

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/router",
        "/account-details/",
        "/accounts/",
        "/admin-user/",
        "/admin-users/",
        "/api-key-details/",
        "/api-keys/",
        "/assets/",
        "/auth/",
        "/brands/",
        "/check-email/",
        "/coins/",
        "/customer-deposit-withdrawal-details/",
        "/customer-profile/",
        "/customers/",
        "/deposit-withdrawal-details/",
        "/deposits-withdrawals/",
        "/fee-settings/",
        "/kyc-limits/",
        "/levels/",
        "/main/",
        "/market-categories/",
        "/market-data-feeds/",
        "/networks/",
        "/nodes/",
        "/order-history/",
        "/org-levels/",
        "/payment-history/",
        "/permission-sections/",
        "/permissions/",
        "/products/",
        "/profile/",
        "/recover-password/",
        "/referral-details/",
        "/referral/",
        "/regions/",
        "/reset-password/",
        "/role/",
        "/roles/",
        "/scanners/",
        "/set-password/",
        "/sign-in/",
        "/sms-providers/",
        "/spot-trading-pairs/",
        "/trading-fees/",
        "/trading-history/",
        "/vaults/",
        "/withdrawal-deposit-settings/",
        "/account-details/account-details/consts",
        "/api-key-details/api-key-details/consts",
        "/customer-profile/customer-profile-route/consts",
        "/deposits-withdrawals/deposit-withdrawals/consts",
        "/fee-settings/fee-settings/consts",
        "/referral-details/referral-details-route/consts",
        "/referral/referral-route/consts"
      ]
    },
    "/": {
      "filePath": "index.ts"
    },
    "/router": {
      "filePath": "router.ts"
    },
    "/account-details/": {
      "filePath": "account-details/index.tsx"
    },
    "/accounts/": {
      "filePath": "accounts/index.tsx"
    },
    "/admin-user/": {
      "filePath": "admin-user/index.tsx"
    },
    "/admin-users/": {
      "filePath": "admin-users/index.tsx"
    },
    "/api-key-details/": {
      "filePath": "api-key-details/index.tsx"
    },
    "/api-keys/": {
      "filePath": "api-keys/index.tsx"
    },
    "/assets/": {
      "filePath": "assets/index.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/brands/": {
      "filePath": "brands/index.tsx"
    },
    "/check-email/": {
      "filePath": "check-email/index.tsx"
    },
    "/coins/": {
      "filePath": "coins/index.tsx"
    },
    "/customer-deposit-withdrawal-details/": {
      "filePath": "customer-deposit-withdrawal-details/index.tsx"
    },
    "/customer-profile/": {
      "filePath": "customer-profile/index.tsx"
    },
    "/customers/": {
      "filePath": "customers/index.tsx"
    },
    "/deposit-withdrawal-details/": {
      "filePath": "deposit-withdrawal-details/index.tsx"
    },
    "/deposits-withdrawals/": {
      "filePath": "deposits-withdrawals/index.tsx"
    },
    "/fee-settings/": {
      "filePath": "fee-settings/index.tsx"
    },
    "/kyc-limits/": {
      "filePath": "kyc-limits/index.tsx"
    },
    "/levels/": {
      "filePath": "levels/index.tsx"
    },
    "/main/": {
      "filePath": "main/index.tsx"
    },
    "/market-categories/": {
      "filePath": "market-categories/index.tsx"
    },
    "/market-data-feeds/": {
      "filePath": "market-data-feeds/index.tsx"
    },
    "/networks/": {
      "filePath": "networks/index.tsx"
    },
    "/nodes/": {
      "filePath": "nodes/index.tsx"
    },
    "/order-history/": {
      "filePath": "order-history/index.tsx"
    },
    "/org-levels/": {
      "filePath": "org-levels/index.tsx"
    },
    "/payment-history/": {
      "filePath": "payment-history/index.tsx"
    },
    "/permission-sections/": {
      "filePath": "permission-sections/index.tsx"
    },
    "/permissions/": {
      "filePath": "permissions/index.tsx"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    },
    "/profile/": {
      "filePath": "profile/index.tsx"
    },
    "/recover-password/": {
      "filePath": "recover-password/index.tsx"
    },
    "/referral-details/": {
      "filePath": "referral-details/index.tsx"
    },
    "/referral/": {
      "filePath": "referral/index.tsx"
    },
    "/regions/": {
      "filePath": "regions/index.tsx"
    },
    "/reset-password/": {
      "filePath": "reset-password/index.tsx"
    },
    "/role/": {
      "filePath": "role/index.tsx"
    },
    "/roles/": {
      "filePath": "roles/index.tsx"
    },
    "/scanners/": {
      "filePath": "scanners/index.tsx"
    },
    "/set-password/": {
      "filePath": "set-password/index.tsx"
    },
    "/sign-in/": {
      "filePath": "sign-in/index.tsx"
    },
    "/sms-providers/": {
      "filePath": "sms-providers/index.tsx"
    },
    "/spot-trading-pairs/": {
      "filePath": "spot-trading-pairs/index.tsx"
    },
    "/trading-fees/": {
      "filePath": "trading-fees/index.tsx"
    },
    "/trading-history/": {
      "filePath": "trading-history/index.tsx"
    },
    "/vaults/": {
      "filePath": "vaults/index.tsx"
    },
    "/withdrawal-deposit-settings/": {
      "filePath": "withdrawal-deposit-settings/index.tsx"
    },
    "/account-details/account-details/consts": {
      "filePath": "account-details/account-details.consts.ts"
    },
    "/api-key-details/api-key-details/consts": {
      "filePath": "api-key-details/api-key-details.consts.ts"
    },
    "/customer-profile/customer-profile-route/consts": {
      "filePath": "customer-profile/customer-profile-route.consts.ts"
    },
    "/deposits-withdrawals/deposit-withdrawals/consts": {
      "filePath": "deposits-withdrawals/deposit-withdrawals.consts.ts"
    },
    "/fee-settings/fee-settings/consts": {
      "filePath": "fee-settings/fee-settings.consts.ts"
    },
    "/referral-details/referral-details-route/consts": {
      "filePath": "referral-details/referral-details-route.consts.ts"
    },
    "/referral/referral-route/consts": {
      "filePath": "referral/referral-route.consts.ts"
    }
  }
}
ROUTE_MANIFEST_END */
